GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRXJpa2EiLCJpYXQiOjE2NDEwMTYzMjMsImV4cCI6MTY0MTAxNjMzOH0.d5rZNkZoQigqUt2yd2SC0v1y_QfGBYhiXONdrqT2BWg

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRXJpa2EiLCJpYXQiOjE2NDEwMTYyODN9.oEqSGzdHrDOrfNkjLm8JoK5wt0QONGYtES-tvvi1DOk"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRXJpa2EiLCJpYXQiOjE2NDEwMTYzMjMsImV4cCI6MTY0MTAxNjMzOH0.d5rZNkZoQigqUt2yd2SC0v1y_QfGBYhiXONdrqT2BWg"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Erika"
}